app:
  image: uptownhr/blog
  links:
  - mongo:mongodb
  command: node /data/app.js
  environment:
    VIRTUAL_HOST: "jlee.biz,www.jlee.biz"
    MONGODB: mongodb://mongodb:27017/blog
    TITLE: 'Full stack development blog'
    AUTHOR: 'James Lee'
  volumes:
  - ./:/data
mongo:
 image: mongo